server:
  port: 8081
spring:
  security:
    debug: true
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: static/**,public/**
    livereload:
      enabled: true
      port: 35729
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/food_app
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        connection:
          handling_mode: DELAYED_ACQUISITION_AND_HOLD
          provider_disables_autocommit: false
        default_schema: public
        globally_quoted_identifiers: true
        globally_quoted_identifiers_skip_column_definitions: true
jwt:
  cookie-max-age: 60000  # 1 phút cho cookie
  accessTokenExpiration: 60000  # 1 phút cho access token (test)
  refreshTokenExpiration: 604800000  # 7 ngày cho refresh token
  resetTokenExpiration: 300000  # 5 phút cho reset token
  secretKey: 4dVgNvOxWTz2PKJZqCYFoh+AXX0l2OVHoCTfN9ZdXGs=
  resetKey: 4dVgNvOxWTz2PKJZqCYFoh+AXX0l2OVHoCTfN9ZdXGs=
  refreshKey: RKyKtM34VufukHK6sSPlQdDA8wBOHCYUygwIp6Fekco=

vnpay:
  # URL để chuyển hướng người dùng đến cổng thanh toán
  pay-url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html

  # URL để VNPay gọi lại sau khi người dùng thanh toán xong (phải khớp với endpoint trong controller)
  # Lưu ý: Phần domain sẽ được lấy tự động từ request, ở đây chỉ cần path
  return-url: /api/payment/vnpay-payment-return

  # Mã website (Terminal ID) do VNPay cung cấp
  #tmn-code: T2NFMFM4
  #tmn-code: EEIFB4OW
  tmn-code: HXTJXVB0

  # Chuỗi bí mật (Hash Secret) do VNPay cung cấp
  #hash-secret: W27ZTGD9MHB8GNEOLFZPLUI2NNWD1UUX
  #hash-secret: IJCIOEJ17JGYD7VCCC63NCHA2ID5TV2E
  hash-secret: ICSSV3402R1F5XMADPMRKDXZM8ZW27EO
  # API URL để thực hiện các thao tác khác như truy vấn, hoàn tiền (nếu cần)
  api-url: https://sandbox.vnpayment.vn/merchant_webapi/api/transaction

  # Phiên bản API đang sử dụng
  version: 2.1.0

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
  sendgrid:
    api-key: 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
    from-email: blandboy2023@gmail.com
open-api:
  service:
    api-doc: spring-food
    server: http://localhost:8081
    title: Spring Food - Food For Spring
    version: 1.0.0

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.web.FilterChainProxy: DEBUG
    org.springframework.security.web.access.ExceptionTranslationFilter: DEBUG
    org.springframework.security.authentication: DEBUG
