server:
  port: 8081
spring:
  security:
    debug: true
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: static/**,public/**
    livereload:
      enabled: true
      port: 35729
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/food_app
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: public
        globally_quoted_identifiers: true
        globally_quoted_identifiers_skip_column_definitions: true
jwt:
  cookie-max-age: 60000  # 1 phút cho cookie
  accessTokenExpiration: 60000  # 1 phút cho access token (test)
  refreshTokenExpiration: 604800000  # 7 ngày cho refresh token
  resetTokenExpiration: 300000  # 5 phút cho reset token
  secretKey: 4dVgNvOxWTz2PKJZqCYFoh+AXX0l2OVHoCTfN9ZdXGs=
  resetKey: 4dVgNvOxWTz2PKJZqCYFoh+AXX0l2OVHoCTfN9ZdXGs=
  refreshKey: RKyKtM34VufukHK6sSPlQdDA8wBOHCYUygwIp6Fekco=


springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
  sendgrid:
    api-key: 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
    from-email: blandboy2023@gmail.com
open-api:
  service:
    api-doc: spring-food
    server:  http://localhost:8081
    title: Spring Food - Food For Spring
    version: 1.0.0

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.web.FilterChainProxy: DEBUG
    org.springframework.security.web.access.ExceptionTranslationFilter: DEBUG
    org.springframework.security.authentication: DEBUG
