syntax = "proto3";

package com.viettel.client.authentication;

import "google/protobuf/timestamp.proto";
import "google/protobuf/wrappers.proto";
import "google/protobuf/any.proto";
import "google/protobuf/empty.proto";

import "authentication/common.proto";

option java_multiple_files = true;
option java_package = "com.viettel.client.authentication";

service LoginConfigService {
  rpc saveConfig (LoginConfigDTO) returns (LoginConfigDTO) {
  }

  rpc getAllConfigs (PageRequest) returns (PageableLoginConfigDTO) {
  }
}

message PageableLoginConfigDTO {
  repeated LoginConfigDTO data = 1;
  optional int64 totalElement = 2;
  optional int32 totalPage = 3;
}