spring.application.name=product-service

springfood.client.enabled=true
springfood.client.default-protocol=rest
springfood.client.services.log-actions.name=log-actions
springfood.client.services.log-actions.protocol=rest
springfood.client.services.log-actions.url=http://localhost:8094
springfood.client.services.log-actions.enabled=true
