package com.theblood.springfood.chat.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class BlockedUserAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBlockedUserAllPropertiesEquals(BlockedUser expected, BlockedUser actual) {
        assertBlockedUserAutoGeneratedPropertiesEquals(expected, actual);
        assertBlockedUserAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBlockedUserAllUpdatablePropertiesEquals(BlockedUser expected, BlockedUser actual) {
        assertBlockedUserUpdatableFieldsEquals(expected, actual);
        assertBlockedUserUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBlockedUserAutoGeneratedPropertiesEquals(BlockedUser expected, BlockedUser actual) {
        // empty method
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBlockedUserUpdatableFieldsEquals(BlockedUser expected, BlockedUser actual) {
        assertThat(actual)
            .as("Verify BlockedUser relevant properties")
            .satisfies(a -> assertThat(a.getBlockId()).as("check blockId").isEqualTo(expected.getBlockId()))
            .satisfies(a -> assertThat(a.getBlockerId()).as("check blockerId").isEqualTo(expected.getBlockerId()))
            .satisfies(a -> assertThat(a.getBlockedUserId()).as("check blockedUserId").isEqualTo(expected.getBlockedUserId()))
            .satisfies(a -> assertThat(a.getReason()).as("check reason").isEqualTo(expected.getReason()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBlockedUserUpdatableRelationshipsEquals(BlockedUser expected, BlockedUser actual) {
        // empty method
    }
}
