package com.theblood.springfood.chat.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ConversationParticipantAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConversationParticipantAllPropertiesEquals(ConversationParticipant expected, ConversationParticipant actual) {
        assertConversationParticipantAutoGeneratedPropertiesEquals(expected, actual);
        assertConversationParticipantAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConversationParticipantAllUpdatablePropertiesEquals(
        ConversationParticipant expected,
        ConversationParticipant actual
    ) {
        assertConversationParticipantUpdatableFieldsEquals(expected, actual);
        assertConversationParticipantUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConversationParticipantAutoGeneratedPropertiesEquals(
        ConversationParticipant expected,
        ConversationParticipant actual
    ) {
        // empty method
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConversationParticipantUpdatableFieldsEquals(
        ConversationParticipant expected,
        ConversationParticipant actual
    ) {
        assertThat(actual)
            .as("Verify ConversationParticipant relevant properties")
            .satisfies(a -> assertThat(a.getParticipantId()).as("check participantId").isEqualTo(expected.getParticipantId()))
            .satisfies(a -> assertThat(a.getUserId()).as("check userId").isEqualTo(expected.getUserId()))
            .satisfies(a -> assertThat(a.getDisplayName()).as("check displayName").isEqualTo(expected.getDisplayName()))
            .satisfies(a -> assertThat(a.getAvatarUrl()).as("check avatarUrl").isEqualTo(expected.getAvatarUrl()))
            .satisfies(a -> assertThat(a.getRole()).as("check role").isEqualTo(expected.getRole()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getNickname()).as("check nickname").isEqualTo(expected.getNickname()))
            .satisfies(a -> assertThat(a.getLastReadMessageId()).as("check lastReadMessageId").isEqualTo(expected.getLastReadMessageId()))
            .satisfies(a -> assertThat(a.getLastReadAt()).as("check lastReadAt").isEqualTo(expected.getLastReadAt()))
            .satisfies(a -> assertThat(a.getUnreadCount()).as("check unreadCount").isEqualTo(expected.getUnreadCount()))
            .satisfies(a -> assertThat(a.getIsMuted()).as("check isMuted").isEqualTo(expected.getIsMuted()))
            .satisfies(a -> assertThat(a.getMuteUntil()).as("check muteUntil").isEqualTo(expected.getMuteUntil()))
            .satisfies(a -> assertThat(a.getIsPinned()).as("check isPinned").isEqualTo(expected.getIsPinned()))
            .satisfies(a -> assertThat(a.getPinnedAt()).as("check pinnedAt").isEqualTo(expected.getPinnedAt()))
            .satisfies(a -> assertThat(a.getJoinedAt()).as("check joinedAt").isEqualTo(expected.getJoinedAt()))
            .satisfies(a -> assertThat(a.getLeftAt()).as("check leftAt").isEqualTo(expected.getLeftAt()))
            .satisfies(a -> assertThat(a.getAddedBy()).as("check addedBy").isEqualTo(expected.getAddedBy()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConversationParticipantUpdatableRelationshipsEquals(
        ConversationParticipant expected,
        ConversationParticipant actual
    ) {
        assertThat(actual)
            .as("Verify ConversationParticipant relationships")
            .satisfies(a -> assertThat(a.getConversation()).as("check conversation").isEqualTo(expected.getConversation()));
    }
}
