package com.theblood.springfood.chat.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ConversationSettingsAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConversationSettingsAllPropertiesEquals(ConversationSettings expected, ConversationSettings actual) {
        assertConversationSettingsAutoGeneratedPropertiesEquals(expected, actual);
        assertConversationSettingsAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConversationSettingsAllUpdatablePropertiesEquals(ConversationSettings expected, ConversationSettings actual) {
        assertConversationSettingsUpdatableFieldsEquals(expected, actual);
        assertConversationSettingsUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConversationSettingsAutoGeneratedPropertiesEquals(ConversationSettings expected, ConversationSettings actual) {
        // empty method
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConversationSettingsUpdatableFieldsEquals(ConversationSettings expected, ConversationSettings actual) {
        assertThat(actual)
            .as("Verify ConversationSettings relevant properties")
            .satisfies(a -> assertThat(a.getSettingsId()).as("check settingsId").isEqualTo(expected.getSettingsId()))
            .satisfies(a -> assertThat(a.getOnlyAdminCanSend()).as("check onlyAdminCanSend").isEqualTo(expected.getOnlyAdminCanSend()))
            .satisfies(a ->
                assertThat(a.getOnlyAdminCanAddMembers()).as("check onlyAdminCanAddMembers").isEqualTo(expected.getOnlyAdminCanAddMembers())
            )
            .satisfies(a -> assertThat(a.getAutoDeleteDays()).as("check autoDeleteDays").isEqualTo(expected.getAutoDeleteDays()))
            .satisfies(a -> assertThat(a.getAllowReactions()).as("check allowReactions").isEqualTo(expected.getAllowReactions()))
            .satisfies(a -> assertThat(a.getAllowReplies()).as("check allowReplies").isEqualTo(expected.getAllowReplies()))
            .satisfies(a -> assertThat(a.getAllowAttachments()).as("check allowAttachments").isEqualTo(expected.getAllowAttachments()))
            .satisfies(a ->
                assertThat(a.getMaxAttachmentSizeMb()).as("check maxAttachmentSizeMb").isEqualTo(expected.getMaxAttachmentSizeMb())
            )
            .satisfies(a -> assertThat(a.getAllowedFileTypes()).as("check allowedFileTypes").isEqualTo(expected.getAllowedFileTypes()))
            .satisfies(a -> assertThat(a.getShowReadReceipts()).as("check showReadReceipts").isEqualTo(expected.getShowReadReceipts()))
            .satisfies(a ->
                assertThat(a.getShowTypingIndicators()).as("check showTypingIndicators").isEqualTo(expected.getShowTypingIndicators())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConversationSettingsUpdatableRelationshipsEquals(ConversationSettings expected, ConversationSettings actual) {
        // empty method
    }
}
