package com.theblood.springfood.chat.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ConversationAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConversationAllPropertiesEquals(Conversation expected, Conversation actual) {
        assertConversationAutoGeneratedPropertiesEquals(expected, actual);
        assertConversationAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConversationAllUpdatablePropertiesEquals(Conversation expected, Conversation actual) {
        assertConversationUpdatableFieldsEquals(expected, actual);
        assertConversationUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConversationAutoGeneratedPropertiesEquals(Conversation expected, Conversation actual) {
        // empty method
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConversationUpdatableFieldsEquals(Conversation expected, Conversation actual) {
        assertThat(actual)
            .as("Verify Conversation relevant properties")
            .satisfies(a -> assertThat(a.getConversationId()).as("check conversationId").isEqualTo(expected.getConversationId()))
            .satisfies(a -> assertThat(a.getConversationType()).as("check conversationType").isEqualTo(expected.getConversationType()))
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getAvatarUrl()).as("check avatarUrl").isEqualTo(expected.getAvatarUrl()))
            .satisfies(a -> assertThat(a.getReferenceType()).as("check referenceType").isEqualTo(expected.getReferenceType()))
            .satisfies(a -> assertThat(a.getReferenceId()).as("check referenceId").isEqualTo(expected.getReferenceId()))
            .satisfies(a -> assertThat(a.getLastMessagePreview()).as("check lastMessagePreview").isEqualTo(expected.getLastMessagePreview())
            )
            .satisfies(a -> assertThat(a.getLastMessageAt()).as("check lastMessageAt").isEqualTo(expected.getLastMessageAt()))
            .satisfies(a ->
                assertThat(a.getLastMessageSenderId()).as("check lastMessageSenderId").isEqualTo(expected.getLastMessageSenderId())
            )
            .satisfies(a -> assertThat(a.getMessageCount()).as("check messageCount").isEqualTo(expected.getMessageCount()))
            .satisfies(a -> assertThat(a.getIsArchived()).as("check isArchived").isEqualTo(expected.getIsArchived()))
            .satisfies(a -> assertThat(a.getIsPinned()).as("check isPinned").isEqualTo(expected.getIsPinned()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConversationUpdatableRelationshipsEquals(Conversation expected, Conversation actual) {
        assertThat(actual)
            .as("Verify Conversation relationships")
            .satisfies(a -> assertThat(a.getSettings()).as("check settings").isEqualTo(expected.getSettings()));
    }
}
