package com.theblood.springfood.chat.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MessageReactionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMessageReactionAllPropertiesEquals(MessageReaction expected, MessageReaction actual) {
        assertMessageReactionAutoGeneratedPropertiesEquals(expected, actual);
        assertMessageReactionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMessageReactionAllUpdatablePropertiesEquals(MessageReaction expected, MessageReaction actual) {
        assertMessageReactionUpdatableFieldsEquals(expected, actual);
        assertMessageReactionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMessageReactionAutoGeneratedPropertiesEquals(MessageReaction expected, MessageReaction actual) {
        // empty method
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMessageReactionUpdatableFieldsEquals(MessageReaction expected, MessageReaction actual) {
        assertThat(actual)
            .as("Verify MessageReaction relevant properties")
            .satisfies(a -> assertThat(a.getReactionId()).as("check reactionId").isEqualTo(expected.getReactionId()))
            .satisfies(a -> assertThat(a.getUserId()).as("check userId").isEqualTo(expected.getUserId()))
            .satisfies(a -> assertThat(a.getEmoji()).as("check emoji").isEqualTo(expected.getEmoji()))
            .satisfies(a -> assertThat(a.getEmojiDisplay()).as("check emojiDisplay").isEqualTo(expected.getEmojiDisplay()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMessageReactionUpdatableRelationshipsEquals(MessageReaction expected, MessageReaction actual) {
        assertThat(actual)
            .as("Verify MessageReaction relationships")
            .satisfies(a -> assertThat(a.getMessage()).as("check message").isEqualTo(expected.getMessage()));
    }
}
