package com.theblood.springfood.chat.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MessageReportAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMessageReportAllPropertiesEquals(MessageReport expected, MessageReport actual) {
        assertMessageReportAutoGeneratedPropertiesEquals(expected, actual);
        assertMessageReportAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMessageReportAllUpdatablePropertiesEquals(MessageReport expected, MessageReport actual) {
        assertMessageReportUpdatableFieldsEquals(expected, actual);
        assertMessageReportUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMessageReportAutoGeneratedPropertiesEquals(MessageReport expected, MessageReport actual) {
        // empty method
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMessageReportUpdatableFieldsEquals(MessageReport expected, MessageReport actual) {
        assertThat(actual)
            .as("Verify MessageReport relevant properties")
            .satisfies(a -> assertThat(a.getReportId()).as("check reportId").isEqualTo(expected.getReportId()))
            .satisfies(a -> assertThat(a.getReporterId()).as("check reporterId").isEqualTo(expected.getReporterId()))
            .satisfies(a -> assertThat(a.getMessageId()).as("check messageId").isEqualTo(expected.getMessageId()))
            .satisfies(a -> assertThat(a.getReason()).as("check reason").isEqualTo(expected.getReason()))
            .satisfies(a -> assertThat(a.getDetails()).as("check details").isEqualTo(expected.getDetails()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getReviewedBy()).as("check reviewedBy").isEqualTo(expected.getReviewedBy()))
            .satisfies(a -> assertThat(a.getReviewedAt()).as("check reviewedAt").isEqualTo(expected.getReviewedAt()))
            .satisfies(a -> assertThat(a.getReviewNotes()).as("check reviewNotes").isEqualTo(expected.getReviewNotes()))
            .satisfies(a -> assertThat(a.getActionTaken()).as("check actionTaken").isEqualTo(expected.getActionTaken()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMessageReportUpdatableRelationshipsEquals(MessageReport expected, MessageReport actual) {
        // empty method
    }
}
