package com.theblood.springfood.chat.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MessageReadReceiptAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMessageReadReceiptAllPropertiesEquals(MessageReadReceipt expected, MessageReadReceipt actual) {
        assertMessageReadReceiptAutoGeneratedPropertiesEquals(expected, actual);
        assertMessageReadReceiptAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMessageReadReceiptAllUpdatablePropertiesEquals(MessageReadReceipt expected, MessageReadReceipt actual) {
        assertMessageReadReceiptUpdatableFieldsEquals(expected, actual);
        assertMessageReadReceiptUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMessageReadReceiptAutoGeneratedPropertiesEquals(MessageReadReceipt expected, MessageReadReceipt actual) {
        // empty method
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMessageReadReceiptUpdatableFieldsEquals(MessageReadReceipt expected, MessageReadReceipt actual) {
        assertThat(actual)
            .as("Verify MessageReadReceipt relevant properties")
            .satisfies(a -> assertThat(a.getReceiptId()).as("check receiptId").isEqualTo(expected.getReceiptId()))
            .satisfies(a -> assertThat(a.getUserId()).as("check userId").isEqualTo(expected.getUserId()))
            .satisfies(a -> assertThat(a.getReadAt()).as("check readAt").isEqualTo(expected.getReadAt()))
            .satisfies(a -> assertThat(a.getDeviceType()).as("check deviceType").isEqualTo(expected.getDeviceType()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMessageReadReceiptUpdatableRelationshipsEquals(MessageReadReceipt expected, MessageReadReceipt actual) {
        assertThat(actual)
            .as("Verify MessageReadReceipt relationships")
            .satisfies(a -> assertThat(a.getMessage()).as("check message").isEqualTo(expected.getMessage()));
    }
}
