package com.theblood.springfood.chat.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MessageAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMessageAllPropertiesEquals(Message expected, Message actual) {
        assertMessageAutoGeneratedPropertiesEquals(expected, actual);
        assertMessageAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMessageAllUpdatablePropertiesEquals(Message expected, Message actual) {
        assertMessageUpdatableFieldsEquals(expected, actual);
        assertMessageUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMessageAutoGeneratedPropertiesEquals(Message expected, Message actual) {
        // empty method
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMessageUpdatableFieldsEquals(Message expected, Message actual) {
        assertThat(actual)
            .as("Verify Message relevant properties")
            .satisfies(a -> assertThat(a.getMessageId()).as("check messageId").isEqualTo(expected.getMessageId()))
            .satisfies(a -> assertThat(a.getClientMessageId()).as("check clientMessageId").isEqualTo(expected.getClientMessageId()))
            .satisfies(a -> assertThat(a.getSenderId()).as("check senderId").isEqualTo(expected.getSenderId()))
            .satisfies(a -> assertThat(a.getSenderName()).as("check senderName").isEqualTo(expected.getSenderName()))
            .satisfies(a -> assertThat(a.getSenderAvatar()).as("check senderAvatar").isEqualTo(expected.getSenderAvatar()))
            .satisfies(a -> assertThat(a.getMessageType()).as("check messageType").isEqualTo(expected.getMessageType()))
            .satisfies(a -> assertThat(a.getContent()).as("check content").isEqualTo(expected.getContent()))
            .satisfies(a -> assertThat(a.getContentPreview()).as("check contentPreview").isEqualTo(expected.getContentPreview()))
            .satisfies(a -> assertThat(a.getReplyToMessageId()).as("check replyToMessageId").isEqualTo(expected.getReplyToMessageId()))
            .satisfies(a -> assertThat(a.getReplyToPreview()).as("check replyToPreview").isEqualTo(expected.getReplyToPreview()))
            .satisfies(a ->
                assertThat(a.getForwardedFromMessageId()).as("check forwardedFromMessageId").isEqualTo(expected.getForwardedFromMessageId())
            )
            .satisfies(a ->
                assertThat(a.getForwardedFromConversationId())
                    .as("check forwardedFromConversationId")
                    .isEqualTo(expected.getForwardedFromConversationId())
            )
            .satisfies(a -> assertThat(a.getReferenceType()).as("check referenceType").isEqualTo(expected.getReferenceType()))
            .satisfies(a -> assertThat(a.getReferenceId()).as("check referenceId").isEqualTo(expected.getReferenceId()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getIsEdited()).as("check isEdited").isEqualTo(expected.getIsEdited()))
            .satisfies(a -> assertThat(a.getEditedAt()).as("check editedAt").isEqualTo(expected.getEditedAt()))
            .satisfies(a -> assertThat(a.getIsDeleted()).as("check isDeleted").isEqualTo(expected.getIsDeleted()))
            .satisfies(a -> assertThat(a.getDeletedAt()).as("check deletedAt").isEqualTo(expected.getDeletedAt()))
            .satisfies(a -> assertThat(a.getDeletedBy()).as("check deletedBy").isEqualTo(expected.getDeletedBy()))
            .satisfies(a -> assertThat(a.getReactionCount()).as("check reactionCount").isEqualTo(expected.getReactionCount()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMessageUpdatableRelationshipsEquals(Message expected, Message actual) {
        assertThat(actual)
            .as("Verify Message relationships")
            .satisfies(a -> assertThat(a.getConversation()).as("check conversation").isEqualTo(expected.getConversation()));
    }
}
