package com.theblood.springfood.chat.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MessageAttachmentAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMessageAttachmentAllPropertiesEquals(MessageAttachment expected, MessageAttachment actual) {
        assertMessageAttachmentAutoGeneratedPropertiesEquals(expected, actual);
        assertMessageAttachmentAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMessageAttachmentAllUpdatablePropertiesEquals(MessageAttachment expected, MessageAttachment actual) {
        assertMessageAttachmentUpdatableFieldsEquals(expected, actual);
        assertMessageAttachmentUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMessageAttachmentAutoGeneratedPropertiesEquals(MessageAttachment expected, MessageAttachment actual) {
        // empty method
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMessageAttachmentUpdatableFieldsEquals(MessageAttachment expected, MessageAttachment actual) {
        assertThat(actual)
            .as("Verify MessageAttachment relevant properties")
            .satisfies(a -> assertThat(a.getAttachmentId()).as("check attachmentId").isEqualTo(expected.getAttachmentId()))
            .satisfies(a -> assertThat(a.getMediaId()).as("check mediaId").isEqualTo(expected.getMediaId()))
            .satisfies(a -> assertThat(a.getAttachmentType()).as("check attachmentType").isEqualTo(expected.getAttachmentType()))
            .satisfies(a -> assertThat(a.getFileName()).as("check fileName").isEqualTo(expected.getFileName()))
            .satisfies(a -> assertThat(a.getFileSize()).as("check fileSize").isEqualTo(expected.getFileSize()))
            .satisfies(a -> assertThat(a.getMimeType()).as("check mimeType").isEqualTo(expected.getMimeType()))
            .satisfies(a -> assertThat(a.getUrl()).as("check url").isEqualTo(expected.getUrl()))
            .satisfies(a -> assertThat(a.getThumbnailUrl()).as("check thumbnailUrl").isEqualTo(expected.getThumbnailUrl()))
            .satisfies(a -> assertThat(a.getWidth()).as("check width").isEqualTo(expected.getWidth()))
            .satisfies(a -> assertThat(a.getHeight()).as("check height").isEqualTo(expected.getHeight()))
            .satisfies(a -> assertThat(a.getDuration()).as("check duration").isEqualTo(expected.getDuration()))
            .satisfies(a -> assertThat(a.getDisplayOrder()).as("check displayOrder").isEqualTo(expected.getDisplayOrder()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMessageAttachmentUpdatableRelationshipsEquals(MessageAttachment expected, MessageAttachment actual) {
        assertThat(actual)
            .as("Verify MessageAttachment relationships")
            .satisfies(a -> assertThat(a.getMessage()).as("check message").isEqualTo(expected.getMessage()));
    }
}
