package com.theblood.springfood.chat.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TypingIndicatorAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTypingIndicatorAllPropertiesEquals(TypingIndicator expected, TypingIndicator actual) {
        assertTypingIndicatorAutoGeneratedPropertiesEquals(expected, actual);
        assertTypingIndicatorAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTypingIndicatorAllUpdatablePropertiesEquals(TypingIndicator expected, TypingIndicator actual) {
        assertTypingIndicatorUpdatableFieldsEquals(expected, actual);
        assertTypingIndicatorUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTypingIndicatorAutoGeneratedPropertiesEquals(TypingIndicator expected, TypingIndicator actual) {
        // empty method
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTypingIndicatorUpdatableFieldsEquals(TypingIndicator expected, TypingIndicator actual) {
        assertThat(actual)
            .as("Verify TypingIndicator relevant properties")
            .satisfies(a -> assertThat(a.getIndicatorId()).as("check indicatorId").isEqualTo(expected.getIndicatorId()))
            .satisfies(a -> assertThat(a.getUserId()).as("check userId").isEqualTo(expected.getUserId()))
            .satisfies(a -> assertThat(a.getUserName()).as("check userName").isEqualTo(expected.getUserName()))
            .satisfies(a -> assertThat(a.getConversationId()).as("check conversationId").isEqualTo(expected.getConversationId()))
            .satisfies(a -> assertThat(a.getStartedAt()).as("check startedAt").isEqualTo(expected.getStartedAt()))
            .satisfies(a -> assertThat(a.getExpiresAt()).as("check expiresAt").isEqualTo(expected.getExpiresAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTypingIndicatorUpdatableRelationshipsEquals(TypingIndicator expected, TypingIndicator actual) {
        // empty method
    }
}
