package com.theblood.springfood.chat.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class UserPresenceAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserPresenceAllPropertiesEquals(UserPresence expected, UserPresence actual) {
        assertUserPresenceAutoGeneratedPropertiesEquals(expected, actual);
        assertUserPresenceAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserPresenceAllUpdatablePropertiesEquals(UserPresence expected, UserPresence actual) {
        assertUserPresenceUpdatableFieldsEquals(expected, actual);
        assertUserPresenceUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserPresenceAutoGeneratedPropertiesEquals(UserPresence expected, UserPresence actual) {
        // empty method
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserPresenceUpdatableFieldsEquals(UserPresence expected, UserPresence actual) {
        assertThat(actual)
            .as("Verify UserPresence relevant properties")
            .satisfies(a -> assertThat(a.getPresenceId()).as("check presenceId").isEqualTo(expected.getPresenceId()))
            .satisfies(a -> assertThat(a.getUserId()).as("check userId").isEqualTo(expected.getUserId()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getStatusMessage()).as("check statusMessage").isEqualTo(expected.getStatusMessage()))
            .satisfies(a -> assertThat(a.getLastSeenAt()).as("check lastSeenAt").isEqualTo(expected.getLastSeenAt()))
            .satisfies(a ->
                assertThat(a.getActiveConversationId()).as("check activeConversationId").isEqualTo(expected.getActiveConversationId())
            )
            .satisfies(a -> assertThat(a.getDeviceType()).as("check deviceType").isEqualTo(expected.getDeviceType()))
            .satisfies(a -> assertThat(a.getDeviceId()).as("check deviceId").isEqualTo(expected.getDeviceId()))
            .satisfies(a -> assertThat(a.getSessionId()).as("check sessionId").isEqualTo(expected.getSessionId()))
            .satisfies(a -> assertThat(a.getLastActivityAt()).as("check lastActivityAt").isEqualTo(expected.getLastActivityAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserPresenceUpdatableRelationshipsEquals(UserPresence expected, UserPresence actual) {
        // empty method
    }
}
