springfood:
  client:
    enabled: true
    default-protocol: rest
    services:
      log-actions:
        name: log-actions
        protocol: rest
        url: http://localhost:8094
        enabled: true
      payment-service:
        name: payment-service
        protocol: rest
        url: http://localhost:8086
        enabled: true
