package com.theblood.common.enums.kafka;

public enum SagaOrderEventType {
    ORDER_CREATED,
    PRODUCT_PROCESSED,
    PRODUCT_PROCESSED_FAILED,
    ORDER_ITEM_PROCESSED,
    ORDER_ITEM_PROCESS_FAILED,
    ONLINE_PAYMENT_PROCESSED,
    ONLINE_PAYMENT_PROCESS_FAILED,
    COD_PAYMENT_PROCESSED,
    COD_PAYMENT_PROCESS_FAILED
}
