package com.theblood.shopservice.domain;

import static com.theblood.shopservice.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class ShopMemberAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertShopMemberAllPropertiesEquals(ShopMember expected, ShopMember actual) {
        assertShopMemberAutoGeneratedPropertiesEquals(expected, actual);
        assertShopMemberAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertShopMemberAllUpdatablePropertiesEquals(ShopMember expected, ShopMember actual) {
        assertShopMemberUpdatableFieldsEquals(expected, actual);
        assertShopMemberUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertShopMemberAutoGeneratedPropertiesEquals(ShopMember expected, ShopMember actual) {
        // empty method
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertShopMemberUpdatableFieldsEquals(ShopMember expected, ShopMember actual) {
        assertThat(actual)
            .as("Verify ShopMember relevant properties")
            .satisfies(a -> assertThat(a.getShopMemberId()).as("check shopMemberId").isEqualTo(expected.getShopMemberId()))
            .satisfies(a -> assertThat(a.getShopId()).as("check shopId").isEqualTo(expected.getShopId()))
            .satisfies(a -> assertThat(a.getUserId()).as("check userId").isEqualTo(expected.getUserId()))
            .satisfies(a -> assertThat(a.getRoleName()).as("check roleName").isEqualTo(expected.getRoleName()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()))
            .satisfies(a -> assertThat(a.getUpdatedAt()).as("check updatedAt").isEqualTo(expected.getUpdatedAt()))
            .satisfies(a -> assertThat(a.getDepartment()).as("check department").isEqualTo(expected.getDepartment()))
            .satisfies(a -> assertThat(a.getJoinDate()).as("check joinDate").isEqualTo(expected.getJoinDate()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getEndDate()).as("check endDate").isEqualTo(expected.getEndDate()))
            .satisfies(a -> assertThat(a.getWorkSchedule()).as("check workSchedule").isEqualTo(expected.getWorkSchedule()))
            .satisfies(a -> assertThat(a.getSalaryType()).as("check salaryType").isEqualTo(expected.getSalaryType()))
            .satisfies(a ->
                assertThat(a.getBaseSalary())
                    .as("check baseSalary")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getBaseSalary())
            )
            .satisfies(a ->
                assertThat(a.getCommission())
                    .as("check commission")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getCommission())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertShopMemberUpdatableRelationshipsEquals(ShopMember expected, ShopMember actual) {
        // empty method
    }
}
