-- Auto-generated by seed-product-images.js
-- Updates products.images with real Pexels-sourced food images uploaded to Cloudflare R2
-- Generated at: 2026-05-15T17:54:22.162Z

BEGIN;

-- Category: burger (3 products, pool=3)
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/burger/1.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = 'f6fa6857-ec8c-44aa-bde8-5eee933389ae'; -- Burger Bò
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/burger/2.jpg","https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/burger/3.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = '3d28baf2-68cf-42fb-9ded-7bd909fca956'; -- Burger Gà
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/burger/3.jpg","https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/burger/1.jpg","https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/burger/2.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = '74484270-84e4-4299-ab7d-f54d91897a67'; -- Burger Phô Mai

-- Category: banh-bao (3 products, pool=3)
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/banh-bao/1.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = '7629e122-c963-4457-bb3c-d85f0b417d90'; -- Bánh Bao Kim Sa
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/banh-bao/2.jpg","https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/banh-bao/3.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = 'a378bfd4-e5ac-4ff6-adf5-ca194306fc6c'; -- Bánh Bao Nhân Thịt
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/banh-bao/3.jpg","https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/banh-bao/1.jpg","https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/banh-bao/2.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = 'b71c017c-781a-4648-85e4-a216ffa3c97c'; -- Bánh Bao Nhân Đậu Xanh

-- Category: banh-mi (8 products, pool=3)
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/banh-mi/1.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = '1be3ac6d-08fe-4ecc-b5fe-e17214c8baf0'; -- Bánh Mì Bò Kho
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/banh-mi/2.jpg","https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/banh-mi/3.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = '08cdd23d-105b-479f-8984-0f66712ea242'; -- Bánh Mì Chả Lụa
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/banh-mi/3.jpg","https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/banh-mi/1.jpg","https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/banh-mi/2.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = '57e4b934-6ecd-4e1b-be4f-afc1b32f5d2f'; -- Bánh Mì Gà
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/banh-mi/1.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = '4ef2ce8c-2f35-4c1a-8c9f-188a353e5c98'; -- Bánh Mì Pate
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/banh-mi/2.jpg","https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/banh-mi/3.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = 'bf21d49f-fe92-4e9a-993f-dc81771cfdc3'; -- Bánh Mì Thịt
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/banh-mi/3.jpg","https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/banh-mi/1.jpg","https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/banh-mi/2.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = 'ef1ff4a7-8564-4cf6-8334-6811323b63b1'; -- Bánh Mì Trứng
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/banh-mi/1.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = 'd2ef7f62-be2f-4a35-bbb9-b872aabfd325'; -- Bánh Mì Xíu Mại
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/banh-mi/2.jpg","https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/banh-mi/3.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = 'df51ecbe-84c3-4a97-ab35-4e3454bdfb5c'; -- Bánh Mì Đặc Biệt

-- Category: banh-trang (2 products, pool=3)
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/banh-trang/1.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = '48a8ed82-f93b-4277-b4a5-e14cb1fb8a93'; -- Bánh Tráng Trộn Khô Bò
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/banh-trang/2.jpg","https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/banh-trang/3.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = 'fca38345-60a7-4c2d-81a3-406ff1841102'; -- Bánh Tráng Trộn Tôm

-- Category: bun-bo-hue (1 products, pool=3)
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/bun-bo-hue/1.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = '0c6b1606-0e58-467f-8e0d-271fda7533c0'; -- Bún Bò Huế

-- Category: bun (6 products, pool=3)
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/bun/1.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = '334daa63-de32-474c-b003-672f0fe7d438'; -- Bún Bò Nam Bộ
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/bun/2.jpg","https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/bun/3.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = 'bad1a310-1cc5-4c23-9fc9-1e8bf044f7a5'; -- Bún Cá
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/bun/3.jpg","https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/bun/1.jpg","https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/bun/2.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = 'a832175d-4fdd-4d38-84e9-a9fad28022ad'; -- Bún Măng Vịt
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/bun/1.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = '8a286276-4d2b-4697-aeef-0b1e06a63520'; -- Bún Mọc
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/bun/2.jpg","https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/bun/3.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = '2c14eb39-92eb-4614-ba7d-a08a336dc5ff'; -- Bún Riêu
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/bun/3.jpg","https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/bun/1.jpg","https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/bun/2.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = '879a4c0b-9ba9-46d7-879c-d71ae94e820e'; -- Bún Ốc

-- Category: bun-cha (1 products, pool=3)
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/bun-cha/1.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = 'cce00913-a005-437e-a184-a599c6a018c3'; -- Bún Chả

-- Category: bun-thit-nuong (1 products, pool=3)
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/bun-thit-nuong/1.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = '489160c6-de9f-4d4f-898b-af19846f7dcb'; -- Bún Thịt Nướng

-- Category: bun-dau (1 products, pool=3)
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/bun-dau/1.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = '32ba8b67-8b29-4464-882d-5f1a54b9f85e'; -- Bún Đậu Mắm Tôm

-- Category: cf-sua-da (3 products, pool=3)
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/cf-sua-da/1.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = '49a54aa3-f156-411a-9e49-095d2e84b13c'; -- Bạc Xỉu
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/cf-sua-da/2.jpg","https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/cf-sua-da/3.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = '4038fcd3-325f-424b-afa6-edb173eec601'; -- Cà Phê Sữa Đá
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/cf-sua-da/3.jpg","https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/cf-sua-da/1.jpg","https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/cf-sua-da/2.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = 'e8d12f7c-a819-4985-aac6-3fa256219dd9'; -- Cà Phê Đen Đá

-- Category: bach-tuoc (2 products, pool=3)
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/bach-tuoc/1.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = '7f95ca3c-0efd-4889-a707-45af748c7139'; -- Bạch Tuộc Nướng
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/bach-tuoc/2.jpg","https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/bach-tuoc/3.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = 'e32d68fc-f81e-4051-ac08-c9183fa8ce3f'; -- Bạch Tuộc Xào

-- Category: cappuccino (1 products, pool=3)
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/cappuccino/1.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = 'c1fcfe39-7fac-48e1-b1af-36ea70c62002'; -- Cappuccino

-- Category: chao (5 products, pool=3)
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/chao/1.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = '4b89d6e2-dbbd-45ef-9932-319991292e16'; -- Cháo Cá
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/chao/2.jpg","https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/chao/3.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = '633116ae-171b-4664-8313-673eee461d05'; -- Cháo Gà
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/chao/3.jpg","https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/chao/1.jpg","https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/chao/2.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = '8b3ada81-e5b1-4c9f-9a61-87c2565aaa8d'; -- Cháo Hải Sản
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/chao/1.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = 'a5f76693-32e6-40a0-9154-00f0367ac057'; -- Cháo Lòng
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/chao/2.jpg","https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/chao/3.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = 'b93d57a7-caeb-4e05-be37-7c6eedf2a952'; -- Cháo Thịt Bằm

-- Category: che (8 products, pool=3)
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/che/1.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = 'fea8f178-1cd6-4a98-b26b-564a56794b45'; -- Chè Bà Ba
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/che/2.jpg","https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/che/3.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = '8173623d-a3b3-4533-aa47-7f8dc7c6948c'; -- Chè Bưởi
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/che/3.jpg","https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/che/1.jpg","https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/che/2.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = '4da4a102-6068-46a1-aeef-a2d6ef68ec26'; -- Chè Khúc Bạch
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/che/1.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = '934437b4-3551-46bf-8604-e31231a9018e'; -- Chè Sương Sa Hột Lựu
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/che/2.jpg","https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/che/3.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = '67fd69e4-66a3-4c1a-9e37-a200e6155a77'; -- Chè Thái
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/che/3.jpg","https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/che/1.jpg","https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/che/2.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = 'e170249e-8133-4325-beac-a2b505f55af7'; -- Chè Thập Cẩm
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/che/1.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = 'd450b79b-3676-4528-8c04-6ef5dea4faa0'; -- Chè Trôi Nước
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/che/2.jpg","https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/che/3.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = '7f8a77b8-4271-41ea-8670-9f7c74a13755'; -- Chè Đậu Đỏ

-- Category: cha (2 products, pool=3)
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/cha/1.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = 'b7a47d4d-8294-4ba3-a482-84a84ae60c05'; -- Chả Cá
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/cha/2.jpg","https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/cha/3.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = 'efded217-ef54-4a74-a3a9-2f6f800c760e'; -- Chả Lụa

-- Category: cha-gio (6 products, pool=3)
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/cha-gio/1.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = '384f80f7-9402-49cf-a7e1-a472e7ecb30c'; -- Chả Giò
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/cha-gio/2.jpg","https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/cha-gio/3.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = '78ae226b-8df5-4fa4-80a1-6911610b501d'; -- Chả Giò Hải Sản
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/cha-gio/3.jpg","https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/cha-gio/1.jpg","https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/cha-gio/2.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = '31a19b78-f185-4830-85e8-9fc327f766a0'; -- Chả Giò Rế
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/cha-gio/1.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = 'a57fca61-4b46-4f85-b22a-12e43f2278d4'; -- Chả Ram
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/cha-gio/2.jpg","https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/cha-gio/3.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = '423e0130-9c7a-4d5e-aab3-8d487d8484c0'; -- Nem Chua Rán
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/cha-gio/3.jpg","https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/cha-gio/1.jpg","https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/cha-gio/2.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = 'cf3f7b1a-2f42-4296-9947-19ebfa5a8928'; -- Nem Rán

-- Category: cua-ghe (2 products, pool=3)
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/cua-ghe/1.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = 'b8333156-b033-4f79-a17e-e934cc4d850f'; -- Cua Rang Me
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/cua-ghe/2.jpg","https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/cua-ghe/3.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = 'a19d8d97-08ec-4c2c-ad52-b28ead6f958b'; -- Ghẹ Rang Muối

-- Category: cf-dua (1 products, pool=3)
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/cf-dua/1.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = '20868d99-f684-4e9f-bd4d-9dc31f82ba23'; -- Cà Phê Dừa

-- Category: cf-trung (1 products, pool=3)
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/cf-trung/1.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = '078e3976-9b1b-4c17-b193-1fcf1eb99c06'; -- Cà Phê Trứng

-- Category: ca (3 products, pool=2)
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/ca/1.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = '612fd257-9094-408e-904b-d1d907204068'; -- Cá Diêu Hồng Chiên
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/ca/2.jpg","https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/ca/1.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = 'eeb25412-7b3f-45c9-a62d-6ade09303713'; -- Cá Lóc Kho Tộ
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/ca/1.jpg","https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/ca/2.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = '2e2c32c7-68fe-4940-b6f4-12399f96a082'; -- Cá Nướng Muối Ớt

-- Category: com (5 products, pool=3)
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/com/1.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = '3a1d1892-b158-45a6-888a-adbc4d0ca7e8'; -- Cơm Bò Lúc Lắc
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/com/2.jpg","https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/com/3.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = 'b822414a-6949-4c96-a9f0-7c74838a89c7'; -- Cơm Cá Kho
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/com/3.jpg","https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/com/1.jpg","https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/com/2.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = '9a1f9f70-b630-48a0-b4b1-f41931f9d1e0'; -- Cơm Hải Sản
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/com/1.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = 'a01d4cd2-c9f9-4217-84f4-2ab05c53c04f'; -- Cơm Hến
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/com/2.jpg","https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/com/3.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = 'd1143463-fc63-4d9d-8256-df3b73f3e8a5'; -- Cơm Niêu

-- Category: com-chien (3 products, pool=3)
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/com-chien/1.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = 'e99e5887-3c12-473c-9a5f-9ebc3ba29826'; -- Cơm Chiên Dương Châu
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/com-chien/2.jpg","https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/com-chien/3.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = 'b915d2a5-ff24-41d8-8576-35f4341c8080'; -- Cơm Chiên Hải Sản
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/com-chien/3.jpg","https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/com-chien/1.jpg","https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/com-chien/2.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = '23f42703-16f4-49c1-974d-c6fafbccbb6c'; -- Cơm Rang Thập Cẩm

-- Category: com-ga (2 products, pool=3)
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/com-ga/1.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = 'bd48a3c2-2a01-4213-9885-e1901c59be18'; -- Cơm Gà Teriyaki
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/com-ga/2.jpg","https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/com-ga/3.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = '430fda25-0b36-42f5-a795-c78c6165da62'; -- Cơm Gà Xối Mỡ

-- Category: com-tam (2 products, pool=3)
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/com-tam/1.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = 'a4354a39-f035-427e-9cb8-d262998f4bc0'; -- Cơm Sườn Bì Chả
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/com-tam/2.jpg","https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/com-tam/3.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = 'faeeaa0a-85f8-476a-b8df-4f1d74090b0e'; -- Cơm Tấm Sườn

-- Category: espresso (1 products, pool=3)
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/espresso/1.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = '744e2664-a1cd-4661-a85d-b01aa08322a8'; -- Espresso

-- Category: ga-ran (3 products, pool=3)
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/ga-ran/1.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = '248cfac6-f277-4247-ac9d-8ca78aada44a'; -- Gà Rán Cay
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/ga-ran/2.jpg","https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/ga-ran/3.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = 'f439bdc4-17cb-4dc7-a4b6-5faabf3e6ed6'; -- Gà Rán Giòn
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/ga-ran/3.jpg","https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/ga-ran/1.jpg","https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/ga-ran/2.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = '6cf65d91-2450-4742-bd58-e650d01a8bfe'; -- Gà Rán Phô Mai

-- Category: ha-cao (1 products, pool=3)
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/ha-cao/1.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = '34db57ea-41f0-4e8d-9e89-0ceec951418e'; -- Há Cảo

-- Category: khoai-tay (1 products, pool=3)
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/khoai-tay/1.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = 'd3719a8d-f96e-41c6-8e43-f852ec29c789'; -- Khoai Tây Chiên

-- Category: latte (1 products, pool=3)
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/latte/1.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = 'e23fc401-f3e7-4600-8dc2-24a28061d764'; -- Latte

-- Category: lau (10 products, pool=3)
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/lau/1.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = 'd3f4009d-db4b-47dc-a7ea-49f12eac9d73'; -- Lẩu Bò Mỹ
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/lau/2.jpg","https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/lau/3.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = 'e95aba29-80c1-4c7a-92f1-50279813bf8e'; -- Lẩu Bò Nhúng Dấm
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/lau/3.jpg","https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/lau/1.jpg","https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/lau/2.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = '3e31bf00-3de9-4d18-81e4-c9935ef94dd8'; -- Lẩu Bò Nấm
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/lau/1.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = '2f9793fb-e8f4-4c51-8742-e72714753e94'; -- Lẩu Cá Kèo
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/lau/2.jpg","https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/lau/3.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = '8758c2ee-307b-455e-a383-35e74bc5b2d2'; -- Lẩu Gà Lá É
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/lau/3.jpg","https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/lau/1.jpg","https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/lau/2.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = 'dc8b8bae-97d2-410c-9cd3-ec04c75ce303'; -- Lẩu Hải Sản Chua Cay
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/lau/1.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = '8f5b412a-bf9f-45ec-a8f0-8bc9e3ec6933'; -- Lẩu Hải Sản Nấm
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/lau/2.jpg","https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/lau/3.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = 'd56c450a-f299-4f97-8e61-d41a9df565a3'; -- Lẩu Thái Bò
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/lau/3.jpg","https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/lau/1.jpg","https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/lau/2.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = '9636a1e5-ad5d-4fae-9735-b4e36400c1b2'; -- Lẩu Thái Gà
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/lau/1.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = 'bc788457-de3f-4851-93a5-e8281f048fbf'; -- Lẩu Thái Hải Sản

-- Category: muc (2 products, pool=3)
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/muc/1.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = '74635b2e-268e-453a-a7a7-b3adb2a5d738'; -- Mực Nướng Sa Tế
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/muc/2.jpg","https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/muc/3.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = '4bfcfee8-36b0-4532-ba00-6271ebd0e2ca'; -- Mực Xào Sa Tế

-- Category: nem-cuon (1 products, pool=3)
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/nem-cuon/1.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = 'cd0456d2-2858-447f-8160-bc1b110d900f'; -- Nem Cuốn

-- Category: nem-lui (1 products, pool=3)
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/nem-lui/1.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = '408c955b-0570-4f59-bcb6-34a2edc2b045'; -- Nem Lui

-- Category: nem-nuong (1 products, pool=3)
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/nem-nuong/1.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = '5347b9d4-b35e-40b4-b2cd-ab2c861ba6a2'; -- Nem Nướng Nha Trang

-- Category: ngheu (2 products, pool=3)
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/ngheu/1.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = '0d32f367-b34a-48bc-af47-2eeef961b026'; -- Nghêu Hấp Xả
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/ngheu/2.jpg","https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/ngheu/3.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = '8ea4fdaf-9de9-4f1d-a60d-5759f927b02b'; -- Nghêu Nướng Phô Mai

-- Category: nuoc-ep (10 products, pool=3)
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/nuoc-ep/1.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = '2f58a731-2fb7-46ec-aab1-a4f33f0c9945'; -- Nước Ép Bưởi
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/nuoc-ep/2.jpg","https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/nuoc-ep/3.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = '4178dc01-73ff-4c57-836f-c630922a4377'; -- Nước Ép Cam
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/nuoc-ep/3.jpg","https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/nuoc-ep/1.jpg","https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/nuoc-ep/2.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = 'edb4121e-e8f8-46ef-a1bc-b232e204d4e2'; -- Nước Ép Chanh
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/nuoc-ep/1.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = '21087324-8be6-4caa-923c-dbf12c9a8b4a'; -- Nước Ép Cà Rốt
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/nuoc-ep/2.jpg","https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/nuoc-ep/3.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = '2194d197-2fa1-4169-9488-22487b2af114'; -- Nước Ép Dâu
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/nuoc-ep/3.jpg","https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/nuoc-ep/1.jpg","https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/nuoc-ep/2.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = '3e2c7272-07a5-438e-936a-f9792e1a364d'; -- Nước Ép Dưa Hấu
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/nuoc-ep/1.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = 'bd706043-8535-44fc-b705-80d29934862e'; -- Nước Ép Dứa
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/nuoc-ep/2.jpg","https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/nuoc-ep/3.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = '6bbf2954-ac8b-4e1c-97dd-c7cd83d835b8'; -- Nước Ép Thập Cẩm
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/nuoc-ep/3.jpg","https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/nuoc-ep/1.jpg","https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/nuoc-ep/2.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = 'da54e782-157f-45d2-8c3c-f35bfbb6764a'; -- Nước Ép Táo
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/nuoc-ep/1.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = 'b6368285-0f31-41b4-9119-e41ec638f92e'; -- Nước Ép Ổi

-- Category: pho (8 products, pool=3)
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/pho/1.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = 'ff201c31-870a-4de0-a698-93b3d3c942c4'; -- Phở Bò Chín
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/pho/2.jpg","https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/pho/3.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = 'f2b93e98-521e-4180-a929-bcb64de2839f'; -- Phở Bò Kho
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/pho/3.jpg","https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/pho/1.jpg","https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/pho/2.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = '4287f7e9-414a-49e2-89ef-07077a0a7ea8'; -- Phở Bò Tái
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/pho/1.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = 'b68fc7e9-71cd-495d-ad5c-72517f98625f'; -- Phở Bò Viên
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/pho/2.jpg","https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/pho/3.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = '29c641e6-0b6f-45b2-98ec-4abdd64c48b4'; -- Phở Gà
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/pho/3.jpg","https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/pho/1.jpg","https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/pho/2.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = '73c5e1f5-0cf8-4cfd-b51d-267d1b4cf964'; -- Phở Gà Quay
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/pho/1.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = 'd4f6f1c3-fda0-470e-a28f-27d962779783'; -- Phở Sốt Vang
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/pho/2.jpg","https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/pho/3.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = 'c6803a86-7911-4fc3-9b44-c73b44a19578'; -- Phở Đặc Biệt

-- Category: pho-cuon (1 products, pool=3)
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/pho-cuon/1.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = 'b593a314-c40b-4b5e-a9a7-144a41f2802e'; -- Phở Cuốn

-- Category: pho-xao (1 products, pool=3)
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/pho-xao/1.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = '2c439d9b-273f-4190-a40c-88439c3e6230'; -- Phở Xào

-- Category: pizza (3 products, pool=3)
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/pizza/1.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = 'a5b3daa5-e00a-4ba2-91cb-9cf994425dd3'; -- Pizza Hải Sản
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/pizza/2.jpg","https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/pizza/3.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = '2d951d82-ce24-45fc-b643-6e38e727b700'; -- Pizza Thập Cẩm
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/pizza/3.jpg","https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/pizza/1.jpg","https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/pizza/2.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = '59e31c43-00c1-4f59-b8fb-729276d4a9dd'; -- Pizza Xúc Xích

-- Category: sinh-to (10 products, pool=3)
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/sinh-to/1.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = 'c010ab50-db50-474d-b269-4a5186641575'; -- Sinh Tố Bơ
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/sinh-to/2.jpg","https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/sinh-to/3.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = '278ab8b7-ae32-4bcd-a2dc-998dce92d873'; -- Sinh Tố Bơ Sữa Chua
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/sinh-to/3.jpg","https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/sinh-to/1.jpg","https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/sinh-to/2.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = 'edfd7941-a135-4ac9-8609-7345f42fcbca'; -- Sinh Tố Chuối
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/sinh-to/1.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = '93cd83f9-c738-489f-824d-c732e3000976'; -- Sinh Tố Dâu
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/sinh-to/2.jpg","https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/sinh-to/3.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = 'e7a32f45-7dc9-44d7-b237-ad6ee5c832f7'; -- Sinh Tố Dưa Hấu
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/sinh-to/3.jpg","https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/sinh-to/1.jpg","https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/sinh-to/2.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = '31c75c84-40d3-44a8-8124-b2ef14fe7966'; -- Sinh Tố Dừa
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/sinh-to/1.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = 'f2904fb2-c0a3-4e46-9a61-daa416767582'; -- Sinh Tố Mãng Cầu
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/sinh-to/2.jpg","https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/sinh-to/3.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = '5b76cc16-289f-42a0-a052-bd800dc74698'; -- Sinh Tố Sapoche
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/sinh-to/3.jpg","https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/sinh-to/1.jpg","https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/sinh-to/2.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = '848bcd0a-ca56-4f78-a26d-fa72cd07b233'; -- Sinh Tố Thập Cẩm
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/sinh-to/1.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = '02f70647-ec1d-4204-a898-81ec76b36e65'; -- Sinh Tố Xoài

-- Category: so-diep (2 products, pool=3)
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/so-diep/1.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = '4273f2e0-e64e-4d5d-aeca-1964adb94466'; -- Sò Điệp Hấp
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/so-diep/2.jpg","https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/so-diep/3.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = '0c898b54-f0b0-40cf-aaef-bc09afd5ebd5'; -- Sò Điệp Nướng Mỡ Hành

-- Category: bbq (4 products, pool=3)
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/bbq/1.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = 'cfb063b0-b58e-4b2f-bd9b-bc32c2ec5e78'; -- Sườn Non Nướng Mật Ong
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/bbq/2.jpg","https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/bbq/3.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = '1b54aae9-cf57-43bb-ac3b-afe5db1695b9'; -- Sườn Nướng BBQ
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/bbq/3.jpg","https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/bbq/1.jpg","https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/bbq/2.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = '0c275940-6317-47cd-9a0a-25177ceac491'; -- Thịt Ba Chỉ Nướng
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/bbq/1.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = 'fffdc6cd-eeec-42a5-acbf-69201b3e7634'; -- Thịt Xiên Nướng

-- Category: tra (8 products, pool=3)
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/tra/1.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = '45717377-a566-4193-a41f-63b209deb34d'; -- Trà Chanh Leo
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/tra/2.jpg","https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/tra/3.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = '83de88d4-7828-4804-8e9e-e2dee9e75f0b'; -- Trà Dâu
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/tra/3.jpg","https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/tra/1.jpg","https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/tra/2.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = 'e5623733-adc8-402c-a00d-bdb754d2468f'; -- Trà Dứa
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/tra/1.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = '52598add-88b0-4a2e-8a5f-d7133bc41abc'; -- Trà Thanh Long
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/tra/2.jpg","https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/tra/3.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = '96d0558b-a6b0-45b1-8b08-7c7ebbdf8e31'; -- Trà Thập Cẩm
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/tra/3.jpg","https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/tra/1.jpg","https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/tra/2.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = 'ff727402-3ab2-4d21-9317-70c8b8ce3b78'; -- Trà Vải
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/tra/1.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = '6ffc0008-d25d-4885-a27a-cb7898084764'; -- Trà Xoài
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/tra/2.jpg","https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/tra/3.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = '001566d2-1234-4aa5-a2d9-677d5422d375'; -- Trà Đào Cam Sả

-- Category: tra-sua (12 products, pool=3)
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/tra-sua/1.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = '96dbc58d-77fe-40b8-a101-1365363f8eb1'; -- Trà Sữa Caramel
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/tra-sua/2.jpg","https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/tra-sua/3.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = 'a9f33cde-cde8-47c3-a44c-dc54aec1f944'; -- Trà Sữa Dâu
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/tra-sua/3.jpg","https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/tra-sua/1.jpg","https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/tra-sua/2.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = 'bb52c8d3-d97e-4962-ab27-af3ba3a645ea'; -- Trà Sữa Hokkaido
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/tra-sua/1.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = 'af661c6a-10a9-4eee-a964-b1ea59c99ba2'; -- Trà Sữa Khoai Môn
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/tra-sua/2.jpg","https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/tra-sua/3.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = '895e9bf0-73f4-4f55-9e2c-e1fc5d8965ac'; -- Trà Sữa Matcha
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/tra-sua/3.jpg","https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/tra-sua/1.jpg","https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/tra-sua/2.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = 'ce2fe866-9bdf-433f-8a30-d33a594458e4'; -- Trà Sữa Phô Mai
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/tra-sua/1.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = '78e2be04-2c3d-4585-b1d0-f07116b13680'; -- Trà Sữa Socola
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/tra-sua/2.jpg","https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/tra-sua/3.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = '5399cd69-a8f2-4059-8def-6aaa9f573236'; -- Trà Sữa Thái Xanh
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/tra-sua/3.jpg","https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/tra-sua/1.jpg","https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/tra-sua/2.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = '5b68dd98-4694-426d-8392-f31a4d8466a1'; -- Trà Sữa Truyền Thống
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/tra-sua/1.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = '0a388c24-167e-4d0b-8b3b-1b2326025221'; -- Trà Sữa Trân Châu Đường Đen
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/tra-sua/2.jpg","https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/tra-sua/3.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = 'f922202a-9fde-4e35-84e3-3f65236d75a7'; -- Trà Sữa Ô Long
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/tra-sua/3.jpg","https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/tra-sua/1.jpg","https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/tra-sua/2.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = '31074319-c433-48d6-ba8b-09924a7ad70f'; -- Trà Sữa Đào

-- Category: tom (2 products, pool=3)
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/tom/1.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = '3e6d7e45-5591-44b9-a96c-4705d208a72a'; -- Tôm Hấp Bia
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/tom/2.jpg","https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/tom/3.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = 'bd6e360f-1355-4e45-bf71-bec07b143742'; -- Tôm Nướng Muối Ớt

-- Category: xiu-mai (1 products, pool=3)
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/xiu-mai/1.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = '05fae697-9fa0-4388-bf62-14081b498083'; -- Xíu Mại

-- Category: xoi (6 products, pool=3)
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/xoi/1.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = '67227a00-c275-4ca8-a42b-a93127e455a8'; -- Xôi Chả
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/xoi/2.jpg","https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/xoi/3.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = '88ed3103-e003-44b5-bb54-7ec3bb58189c'; -- Xôi Gà
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/xoi/3.jpg","https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/xoi/1.jpg","https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/xoi/2.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = '81cf6232-a133-4452-bd70-3e091dd8120c'; -- Xôi Lạc
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/xoi/1.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = 'e7e8e68c-ac89-4621-9692-2e974a394f31'; -- Xôi Thập Cẩm
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/xoi/2.jpg","https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/xoi/3.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = '2ce4aa11-de4e-4eee-8c4e-5fab53beb876'; -- Xôi Xéo
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/xoi/3.jpg","https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/xoi/1.jpg","https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/xoi/2.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = '97d6bbad-a6e7-4620-8f67-981904446ca2'; -- Xôi Đậu Xanh

-- Category: oc (1 products, pool=3)
UPDATE springfood_product.products SET images = '["https://pub-db7036086154479380d282adb29af0a4.r2.dev/seed/products/oc/1.jpg"]'::jsonb, updated_at = NOW() WHERE product_id = '30fa6fde-9ba6-4c9e-90e5-6277bbd17372'; -- Ốc Hương Xào Bơ Tỏi

COMMIT;
-- Done: 165 updated, 0 skipped