syntax = "proto3";

option java_multiple_files = true;
option java_package = "com.theblood.springfood.common.grpc";
//option java_outer_classname = "ProductProto";

service ProductService {
  rpc ValidateProductCreation (ValidateProductCreationRequest) returns (ValidateProductCreationResponse);
  rpc ValidateProductUpdate (ValidateProductUpdateRequest) returns (ValidateProductUpdateResponse);
}

message ValidateProductCreationRequest {
  string sku = 1;
  string shopId = 2;
  string username = 3; // current user
  string categoryNames = 4;
}
message ValidateProductCreationResponse {
  bool isValid = 1;
  string message = 2;
}
message ValidateProductUpdateRequest{
  string shopId = 1;
  string userId = 2;
}
message ValidateProductUpdateResponse{
  bool isValid = 1;
  string message = 2;
}